#!/bin/bash
echo "PDF安全工具 - GitHub上传脚本"
echo "============================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 登录GitHub (https://github.com/login)"
echo "   用户名: a061318"
echo "   密码: yx061318"
echo ""
echo "2. 创建新仓库："
echo "   - 点击右上角 '+' → 'New repository'"
echo "   - 名称: pdf-secure-tool"
echo "   - 描述: PDF安全工具 - Windows 11免安装版"
echo "   - 选择 Public"
echo "   - 不要勾选 'Add a README file'"
echo "   - 点击 'Create repository'"
echo ""
echo "3. 创建仓库后，复制以下命令在终端执行："
echo ""
echo "   # 切换到工具目录"
echo "   cd ~/.openclaw/workspace/pdf_tool"
echo ""
echo "   # 初始化Git仓库"
echo "   git init"
echo "   git add ."
echo "   git commit -m '初始提交: PDF安全工具'"
echo ""
echo "   # 连接到GitHub仓库（复制创建仓库后显示的URL）"
echo "   git remote add origin https://github.com/a061318/pdf-secure-tool.git"
echo ""
echo "   # 推送代码"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. 触发自动构建："
echo "   - 进入仓库页面：https://github.com/a061318/pdf-secure-tool"
echo "   - 点击 'Actions' 标签页"
echo "   - 选择 'Build PDF Secure Tool EXE' 工作流"
echo "   - 点击 'Run workflow' → 'Run workflow'"
echo "   - 等待约5-10分钟构建完成"
echo ""
echo "5. 下载EXE文件："
echo "   - 构建完成后，进入构建详情"
echo "   - 在 'Artifacts' 部分下载 'PDF安全工具.zip'"
echo "   - 解压得到 'PDF安全工具.exe'"
echo ""
echo "✅ 完成！现在您有了免安装的EXE工具。"