#!/bin/bash

echo "========================================="
echo "PDF安全工具 - GitHub自动构建设置"
echo "========================================="
echo ""

echo "📋 文件清单："
echo "------------"
find . -type f -name "*.py" -o -name "*.md" -o -name "*.txt" -o -name "*.bat" -o -name "*.yml" -o -name "*.sh" | sort
echo ""

echo "🚀 第一步：创建GitHub仓库"
echo "----------------------"
echo "1. 打开浏览器访问：https://github.com/new"
echo "2. 使用以下信息登录："
echo "   用户名: a061318"
echo "   密码: yx061318"
echo "3. 创建新仓库："
echo "   - 名称: pdf-secure-tool"
echo "   - 描述: PDF安全工具 - Windows 11免安装版"
echo "   - 选择: Public"
echo "   - 不要添加 README、.gitignore、license"
echo "4. 点击 'Create repository'"
echo ""

echo "📤 第二步：上传代码到GitHub"
echo "------------------------"
echo "复制并执行以下命令："
echo ""
echo "# 进入工具目录"
echo "cd $(pwd)"
echo ""
echo "# 初始化Git仓库"
echo "git init"
echo "git add ."
echo "git commit -m '初始提交: PDF安全工具'"
echo ""
echo "# 连接到GitHub（使用创建仓库后显示的URL）"
echo "git remote add origin https://github.com/a061318/pdf-secure-tool.git"
echo ""
echo "# 推送代码"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "注意：推送时需要输入GitHub密码"
echo "如果要求token，请访问：https://github.com/settings/tokens"
echo "生成token并用作密码"
echo ""

echo "⚡ 第三步：触发自动构建"
echo "-------------------"
echo "1. 访问：https://github.com/a061318/pdf-secure-tool"
echo "2. 点击 'Actions' 标签页"
echo "3. 选择 'Build PDF Secure Tool EXE'"
echo "4. 点击 'Run workflow' → 'Run workflow'"
echo "5. 等待5-10分钟构建完成"
echo ""

echo "📥 第四步：下载EXE文件"
echo "-------------------"
echo "构建完成后："
echo "1. 进入构建详情页面"
echo "2. 在底部 'Artifacts' 部分"
echo "3. 点击 'PDF安全工具' 下载ZIP"
echo "4. 解压得到 'PDF安全工具.exe'"
echo ""

echo "🎯 EXE工具功能："
echo "--------------"
echo "✅ 免安装 - 双击即可运行"
echo "✅ 图形界面 - 中文操作界面"
echo "✅ 添加水印 - 自定义文本、透明度、角度"
echo "✅ PDF加密 - 设置密码和权限"
echo "✅ 批量处理 - 支持文件夹批量操作"
echo "✅ Windows 11优化 - 专为Win11设计"
echo ""

echo "🔧 技术规格："
echo "-----------"
echo "• 系统要求: Windows 7/8/10/11 (64位)"
echo "• 文件大小: ~20-30MB"
echo "• 加密标准: 128位AES"
echo "• 水印类型: 文字水印"
echo "• 界面语言: 中文"
echo ""

echo "⚠️ 注意事项："
echo "-----------"
echo "1. 杀毒软件可能误报，请添加信任"
echo "2. 首次运行可能需要管理员权限"
echo "3. 确保Windows已安装最新更新"
echo "4. 处理前请备份重要文件"
echo ""

echo "✅ 设置完成！"
echo "现在您可以通过GitHub Actions自动构建EXE文件。"
echo "如需更新工具，只需修改代码并推送即可自动生成新版本。"